networks:
  deploy-guide-dev:
    driver: bridge

services:
  app:
    container_name: deploy-guide
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres_db
    environment:
      - ConnectionStrings__AppContextDb=Host=postgres_db;Port=5432;Database=ZooDb;Username=postgres;Password=admin2

  postgres_db:
    container_name: postgres
    image: postgres:14.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin2
      POSTGRES_DB: ZooDb
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data:

        
    


